version: '3'
services:
  database-client:
    image: panintelligence/mariadb_sql_injector:latest
    environment:
      - PI_DB_SCHEMA_NAME=<DB schema name>
      - PI_DB_PASSWORD=<DB password>
      - PI_DB_USERNAME=<DB username>
      - PI_DB_HOST=<DB host name>
      - SQL_INJECT_BOOL=true
      - SQL_FILE_NAME=<The file name you wish to run in the volume>
    volumes: 
        - .<local directory of where your sql/text file is>:/var/sql
