version: '3'
services:
  dashboard:
    stdin_open: true
    tty: true
    container_name: dashboard-marialess
    image: panintelligence/dashboard-marialess:latest
    ports:
      - "8224:8224"
    expose:
      - "9918"
    volumes:
      - /docker/volumes/panintelligence/keys:/var/panintelligence/Dashboard/keys
      - /docker/volumes/panintelligence/themes:/var/panintelligence/Dashboard/tomcat/webapps/panMISDashboardResources/themes
      - /docker/volumes/panintelligence/licence.xml:/var/panintelligence/Dashboard/tomcat/webapps/panLicenceManager/WEB-INF/classes/licence.xml
    environment:
      - PI_DB_HOST=your.mariadb.com"
      - PI_DB_PORT=3306
      - PI_DB_USERNAME=root
      - PI_DB_PASSWORD=SuperSecurePasswordHere
      - PI_EXTERNAL_DB=true