version: '3'
services:
  dashboard:
    stdin_open: true
    tty: true
    container_name: dashboard
    image: panintelligence/dashboard:latest
    ports:
      - "8224:8224"
    expose:
      - "9918"
    volumes:
      - /docker/volumes/panintelligence/keys:/var/panintelligence/Dashboard/keys
      - /docker/volumes/panintelligence/data:/var/panintelligence/Dashboard/db/data
      - /docker/volumes/panintelligence/themes:/var/panintelligence/Dashboard/tomcat/webapps/panMISDashboardResources/themes
      - /docker/volumes/panintelligence/svg:/var/panintelligence/Dashboard/tomcat/webapps/panMISDashboardResources/svg
      - /docker/volumes/panintelligence/custom_jdbc_drivers:/var/panintelligence/Dashboard/tomcat/custom_jdbc_drivers
    environment:
      - PI_LICENCE=<Licence>...</Licence>